import Foundation

/// Copy on one Mac of the desk, paste on another: what Perch will carry, what it
/// never carries, and the one sentence it records for every decision.
///
/// The rules, agreed with Scott on September 21, 2026 (TODO.md, "Shared
/// clipboard, then file transfer"):
///
/// - Nothing is sent when you copy. When the keyboard arrives on a Mac, that Mac
///   asks the others which of them copied last, and fetches only that copy.
/// - Only Macs already paired in the desk take part, and only while keyboard and
///   mouse sharing is on for the Mac ("Share on this Mac"). That switch is the
///   person's consent for the desk to act across Macs; there is no second one.
/// - Anything a password manager marked concealed, and anything marked transient
///   or generated automatically, is never offered at all (nspasteboard.org).
/// - Only an allowlist of plain types crosses: plain text, rich text, HTML and
///   images. Never an app's private pasteboard types, which can hold anything.
///   Files cross as files, into Downloads (DeskFileTransfer).
/// - Contents, file names, types and exact sizes never reach the log. Sizes are
///   logged as buckets.
enum DeskClipboardType: UInt8, CaseIterable {
    case plainText = 1, richText = 2, html = 3, png = 4, tiff = 5, jpeg = 6

    var identifier: String {
        switch self {
        case .plainText: return "public.utf8-plain-text"
        case .richText: return "public.rtf"
        case .html: return "public.html"
        case .png: return "public.png"
        case .tiff: return "public.tiff"
        case .jpeg: return "public.jpeg"
        }
    }
    var isImage: Bool { self == .png || self == .tiff || self == .jpeg }
    /// One image representation is enough for any app that pastes an image, so
    /// only the first of these present is sent: PNG is lossless and usually far
    /// smaller than the TIFF that sits beside it.
    static let imagePreference: [DeskClipboardType] = [.png, .jpeg, .tiff]
    static func from(identifier: String) -> DeskClipboardType? { allCases.first { $0.identifier == identifier } }
}

/// The marks apps put on a copy to say it must not travel. Any one of them on
/// any item withholds the whole copy, before a byte of its data is read.
enum DeskClipboardMarker {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// Marks some password managers and clipboard tools wrote before the
    /// nspasteboard.org names were agreed. Treating them the same costs nothing.
    static let legacyConcealed: Set<String> = ["com.agilebits.onepassword", "net.antelle.keeweb"]
    static let legacyTransient: Set<String> = ["de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "Pasteboard generator type"]
    /// A copy of files or folders. Their names and icons ride along as text and
    /// images, which must never be pasted in their place.
    static let fileURL = "public.file-url"
    static let legacyFileNames = "NSFilenamesPboardType"
}

/// Why a copy was not shared or a transfer ended. Every refusal and every
/// failure names exactly one of these, in the log and on the wire.
enum DeskClipboardReason: UInt8, CaseIterable {
    case sharingOff = 1, concealed, transient, autoGenerated, unsupported, tooLarge
    case changed, busy, rateLimited, readTimedOut, noCopy, unknownCopy, format
    case timedOut, cancelled, corrupt, newerHere, peerGone, notSupported, writeFailed, sharingOffHere, notReady
    case folders, links, unreadable, unsafeName, noSpace, quarantine

    /// The reason as a phrase that completes "because …". Plain feature terms.
    var text: String {
        switch self {
        case .sharingOff: return "keyboard and mouse sharing is off or paused on that Mac"
        case .concealed: return "it was marked as a password or other concealed item"
        case .transient: return "the app that copied it marked it as temporary"
        case .autoGenerated: return "it was generated automatically, not copied by someone"
        case .unsupported: return "it is not text, rich text, an image or files"
        case .tooLarge: return "it is larger than Perch shares"
        case .changed: return "it changed before it could be sent"
        case .busy: return "that Mac is already sending a copy"
        case .rateLimited: return "it was asked for too often"
        case .readTimedOut: return "the app that copied it did not hand it over in time"
        case .noCopy: return "nothing was copied there since Perch started"
        case .unknownCopy: return "that copy is no longer the newest there"
        case .format: return "the two Macs share copies in different ways"
        case .timedOut: return "the other Mac stopped answering"
        case .cancelled: return "the transfer was cancelled"
        case .corrupt: return "the content arrived damaged or out of order"
        case .newerHere: return "something newer was copied on this Mac"
        case .peerGone: return "the other Mac left the desk"
        case .notSupported: return "that Mac's Perch cannot share copies yet"
        case .writeFailed: return "this Mac could not put it on the clipboard"
        case .sharingOffHere: return "keyboard and mouse sharing is off or paused on this Mac"
        case .notReady: return "this Mac's clipboard has not answered yet"
        case .folders: return "it includes a folder, and folders are not shared yet"
        case .links: return "it includes a link or alias, and Perch sends only the files themselves"
        case .unreadable: return "a file in it could not be read"
        case .unsafeName: return "a file name in it could not be made safe"
        case .noSpace: return "there is not enough space for it on this Mac"
        case .quarantine: return "this Mac could not mark it as downloaded"
        }
    }
}

/// Everything Perch decides about a copy, and the only source of what it logs.
/// The log line is computed from the decision itself, so the two cannot
/// disagree: there is no second place where a reason could be written.
enum DeskClipboardDecision: Equatable {
    /// Requesting side.
    case newestHere
    case alreadyHere(from: String)
    case notShared(from: String, DeskClipboardReason)
    case noAnswer
    case fetching(from: String, transfer: UUID)
    case received(from: String, transfer: UUID, size: String)
    case refusedBy(String, transfer: UUID?, DeskClipboardReason)
    case failed(from: String, transfer: UUID, DeskClipboardReason, detail: String?)
    case discarded(transfer: UUID, DeskClipboardReason)
    /// Serving side.
    case offered(to: String)
    case withheld(to: String, DeskClipboardReason)
    case sent(to: String, transfer: UUID, size: String)
    case refused(to: String, transfer: UUID, DeskClipboardReason)
    case stoppedSending(to: String, transfer: UUID, DeskClipboardReason)
    /// The desk.
    case peerSupports(String, format: UInt8)
    case peerCannot(String, DeskClipboardReason)
    case notAsking(DeskClipboardReason)

    var reason: DeskClipboardReason? {
        switch self {
        case .notShared(_, let reason), .refusedBy(_, _, let reason), .failed(_, _, let reason, _), .discarded(_, let reason),
             .withheld(_, let reason), .refused(_, _, let reason), .stoppedSending(_, _, let reason), .peerCannot(_, let reason),
             .notAsking(let reason): return reason
        default: return nil
        }
    }
    static let category = "clipboard"
    /// What the decision log says. Names Macs, short transfer numbers, reasons
    /// and size buckets only: never contents, names, types or exact sizes.
    var line: String {
        func id(_ value: UUID?) -> String { value.map { " " + String($0.uuidString.prefix(8)) } ?? "" }
        func because(_ reason: DeskClipboardReason) -> String { " because " + reason.text }
        switch self {
        case .newestHere: return "Paste stays as it is: the newest copy on the desk is on this Mac"
        case .alreadyHere(let from): return "Paste stays as it is: this Mac already has the newest copy, from \(from)"
        case .notShared(let from, let reason): return "Did not bring the newest copy from \(from)" + because(reason)
        case .noAnswer: return "Paste stays as it is: no other Mac answered in time"
        case .fetching(let from, let transfer): return "Bringing the newest copy from \(from), transfer\(id(transfer))"
        case .received(let from, let transfer, let size): return "Brought the newest copy from \(from), transfer\(id(transfer)), \(size)"
        case .refusedBy(let from, let transfer, let reason): return "\(from) declined to send its copy\(transfer == nil ? "" : ", transfer" + id(transfer))" + because(reason)
        case .failed(let from, let transfer, let reason, let detail):
            return "Stopped bringing the copy from \(from), transfer\(id(transfer))" + because(reason) + (detail.map { " (\($0))" } ?? "")
        case .discarded(let transfer, let reason): return "Did not use transfer\(id(transfer))" + because(reason)
        case .offered(let to): return "Told \(to) about this Mac's newest copy"
        case .withheld(let to, let reason): return "Did not offer this Mac's newest copy to \(to)" + because(reason)
        case .sent(let to, let transfer, let size): return "Sent this Mac's newest copy to \(to), transfer\(id(transfer)), \(size)"
        case .refused(let to, let transfer, let reason): return "Declined to send this Mac's copy to \(to), transfer\(id(transfer))" + because(reason)
        case .stoppedSending(let to, let transfer, let reason): return "Stopped sending to \(to), transfer\(id(transfer))" + because(reason)
        case .peerSupports(let name, let format): return "\(name) shares copies (format \(format))"
        case .peerCannot(let name, let reason): return "Copies are not shared with \(name)" + because(reason)
        case .notAsking(let reason): return "Did not ask the other Macs for their newest copy" + because(reason)
        }
    }
}

/// How much Perch carries. Conservative first values; each is recorded in
/// TODO.md as Scott's to change.
struct DeskClipboardLimits {
    var plainText = 2 * 1024 * 1024
    /// Each rich text or HTML representation.
    var richText = 8 * 1024 * 1024
    /// The one image representation sent per item.
    var image = 32 * 1024 * 1024
    /// Everything in one copy together, before compression.
    var total = 40 * 1024 * 1024
    var items = 16

    func cap(_ type: DeskClipboardType) -> Int {
        switch type {
        case .plainText: return plainText
        case .richText, .html: return richText
        case .png, .tiff, .jpeg: return image
        }
    }
}

enum DeskClipboardPolicy {
    /// Which representations to read from each item, or why the copy is
    /// withheld. Decided from the types alone, so a concealed copy is refused
    /// before any of its data is read into Perch.
    enum Assessment: Equatable {
        case withheld(DeskClipboardReason)
        case share([[DeskClipboardType]])
        /// Files: their names first, then each file, into Downloads.
        case files
    }
    static func assess(_ items: [[String]], limits: DeskClipboardLimits = .init()) -> Assessment {
        let all = Set(items.flatMap { $0 })
        // Order matters only for which single reason is named; every marker
        // withholds the copy.
        if all.contains(DeskClipboardMarker.concealed) || !all.isDisjoint(with: DeskClipboardMarker.legacyConcealed) { return .withheld(.concealed) }
        if all.contains(DeskClipboardMarker.transient) || !all.isDisjoint(with: DeskClipboardMarker.legacyTransient) { return .withheld(.transient) }
        if all.contains(DeskClipboardMarker.autoGenerated) { return .withheld(.autoGenerated) }
        // A copy of files carries their names and icons too, which must never
        // be pasted in place of the files themselves.
        if all.contains(DeskClipboardMarker.fileURL) { return .files }
        if all.contains(DeskClipboardMarker.legacyFileNames) { return .withheld(.unsupported) }
        guard !items.isEmpty else { return .withheld(.noCopy) }
        guard items.count <= limits.items else { return .withheld(.tooLarge) }
        let plan = items.map { types -> [DeskClipboardType] in
            let text = [DeskClipboardType.plainText, .richText, .html].filter { types.contains($0.identifier) }
            let image = DeskClipboardType.imagePreference.first { types.contains($0.identifier) }
            return text + (image.map { [$0] } ?? [])
        }
        guard plan.contains(where: { !$0.isEmpty }) else { return .withheld(.unsupported) }
        return .share(plan)
    }

    /// Coarse size for the log: a bucket, never the exact number.
    static func sizeBucket(_ bytes: Int) -> String {
        switch bytes {
        case ..<(64 * 1024): return "under 64 KB"
        case ..<(1024 * 1024): return "64 KB to 1 MB"
        case ..<(8 * 1024 * 1024): return "1 to 8 MB"
        case ..<(32 * 1024 * 1024): return "8 to 32 MB"
        case ..<(256 * 1024 * 1024): return "32 to 256 MB"
        default: return "over 256 MB"
        }
    }
}
