import Foundation

/// Copy on one Mac of the desk, paste on another: what Perch will carry, what it
/// never carries, and the one sentence it records for every decision.
///
/// The rules, agreed with Scott on September 21, 2026 (TODO.md, "Shared
/// clipboard, then file transfer"):
///
/// - Scott's design, September 27, 2026, replacing the earlier "nothing is sent
///   when you copy": a copy that is only text, 64 KB or less in all, goes onto
///   every other connected Mac's clipboard as soon as it is copied. Anything
///   else is only announced (its kind, a size bucket and which Mac has it),
///   and comes over when ⌃⌥⌘V brings it, with a small progress popup. After
///   that every ordinary paste works: keyboard, menu or right-click.
/// - Only Macs already paired in the desk take part, and only while keyboard and
///   mouse sharing is on for the Mac ("Share on this Mac"). That switch is the
///   person's consent for the desk to act across Macs; there is no second one.
/// - Anything a password manager marked concealed, and anything marked transient
///   or generated automatically, is never offered at all (nspasteboard.org).
/// - Only an allowlist of plain types crosses: plain text, rich text, HTML and
///   images. Never an app's private pasteboard types, which can hold anything.
///   Files cross as files, staged in a folder of Perch's own (DeskFileTransfer).
/// - Contents, file names, types and exact sizes never reach the log. Sizes are
///   logged as buckets.
enum DeskClipboardType: UInt8, CaseIterable {
    case plainText = 1, richText = 2, html = 3, png = 4, tiff = 5, jpeg = 6

    var identifier: String {
        switch self {
        case .plainText: return "public.utf8-plain-text"
        case .richText: return "public.rtf"
        case .html: return "public.html"
        case .png: return "public.png"
        case .tiff: return "public.tiff"
        case .jpeg: return "public.jpeg"
        }
    }
    var isImage: Bool { self == .png || self == .tiff || self == .jpeg }
    /// One image representation is enough for any app that pastes an image, so
    /// only the first of these present is sent: PNG is lossless and usually far
    /// smaller than the TIFF that sits beside it.
    static let imagePreference: [DeskClipboardType] = [.png, .jpeg, .tiff]
    static func from(identifier: String) -> DeskClipboardType? { allCases.first { $0.identifier == identifier } }
}

/// The marks apps put on a copy to say it must not travel. Any one of them on
/// any item withholds the whole copy, before a byte of its data is read.
enum DeskClipboardMarker {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// Marks some password managers and clipboard tools wrote before the
    /// nspasteboard.org names were agreed. Treating them the same costs nothing.
    static let legacyConcealed: Set<String> = ["com.agilebits.onepassword", "net.antelle.keeweb"]
    static let legacyTransient: Set<String> = ["de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping", "Pasteboard generator type"]
    /// A copy of files or folders. Their names and icons ride along as text and
    /// images, which must never be pasted in their place.
    static let fileURL = "public.file-url"
    static let legacyFileNames = "NSFilenamesPboardType"
    /// Perch's own mark on a copy it brought from another Mac, holding that
    /// copy's identity. A copy carrying it came from the desk and is never
    /// announced or sent on again, whatever else changed: no echo, no relay.
    static let received = "local.scott.perch.desk-copy"
}

/// Why a copy was not shared or a transfer ended. Every refusal and every
/// failure names exactly one of these, in the log and on the wire.
enum DeskClipboardReason: UInt8, CaseIterable {
    case sharingOff = 1, concealed, transient, autoGenerated, unsupported, tooLarge
    case changed, busy, rateLimited, readTimedOut, noCopy, unknownCopy, format
    case timedOut, cancelled, corrupt, newerHere, peerGone, notSupported, writeFailed, sharingOffHere, notReady
    case folders, links, unreadable, unsafeName, noSpace, quarantine
    case received, newerThere

    /// The reason as a phrase that completes "because …". Plain feature terms.
    var text: String {
        switch self {
        case .sharingOff: return "keyboard and mouse sharing is off or paused on that Mac"
        case .concealed: return "it was marked as a password or other concealed item"
        case .transient: return "the app that copied it marked it as temporary"
        case .autoGenerated: return "it was generated automatically, not copied by someone"
        case .unsupported: return "it is not text, rich text, an image or files"
        case .tooLarge: return "it is larger than Perch shares"
        case .changed: return "it changed before it could be sent"
        case .busy: return "that Mac is already sending a copy"
        case .rateLimited: return "it was asked for too often"
        case .readTimedOut: return "the app that copied it did not hand it over in time"
        case .noCopy: return "nothing was copied there since Perch started"
        case .unknownCopy: return "that copy is no longer the newest there"
        case .format: return "the two Macs share copies in different ways"
        case .timedOut: return "the other Mac stopped answering"
        case .cancelled: return "the transfer was cancelled"
        case .corrupt: return "the content arrived damaged or out of order"
        case .newerHere: return "something newer was copied on this Mac"
        case .peerGone: return "the other Mac left the desk"
        case .notSupported: return "that Mac's Perch cannot share copies yet"
        case .writeFailed: return "this Mac could not put it on the clipboard"
        case .sharingOffHere: return "keyboard and mouse sharing is off or paused on this Mac"
        case .notReady: return "this Mac's clipboard has not answered yet"
        case .folders: return "it includes a folder, and folders are not shared yet"
        case .links: return "it includes a link or alias, and Perch sends only the files themselves"
        case .unreadable: return "a file in it could not be read"
        case .unsafeName: return "a file name in it could not be made safe"
        case .noSpace: return "there is not enough space for it on this Mac"
        case .quarantine: return "this Mac could not mark it as downloaded"
        case .received: return "it came from another Mac of the desk"
        case .newerThere: return "something newer was copied on another Mac"
        }
    }
}

/// Everything Perch decides about a copy, and the only source of what it logs.
/// The log line is computed from the decision itself, so the two cannot
/// disagree: there is no second place where a reason could be written.
enum DeskClipboardDecision: Equatable {
    /// This Mac's own copies.
    case announced(to: [String])
    case notAnnounced(DeskClipboardReason)
    /// Another Mac's copies.
    case waiting(from: String)
    case newerElsewhere(from: String)
    case fetching(from: String, transfer: UUID)
    case received(from: String, transfer: UUID, size: String)
    case refusedBy(String, transfer: UUID?, DeskClipboardReason)
    case failed(from: String, transfer: UUID, DeskClipboardReason, detail: String?)
    case discarded(transfer: UUID, DeskClipboardReason)
    /// Bringing it over.
    case bringing(from: String)
    case nothingWaiting
    case notBringing(DeskClipboardReason)
    case askedToBringOver(on: String)
    /// Serving side.
    case sent(to: String, transfer: UUID, size: String)
    case refused(to: String, transfer: UUID, DeskClipboardReason)
    case stoppedSending(to: String, transfer: UUID, DeskClipboardReason)
    /// The desk.
    case peerSupports(String, format: UInt8)
    case peerCannot(String, DeskClipboardReason)
    case cleaned(Int)

    var reason: DeskClipboardReason? {
        switch self {
        case .notAnnounced(let reason), .refusedBy(_, _, let reason), .failed(_, _, let reason, _), .discarded(_, let reason),
             .notBringing(let reason), .refused(_, _, let reason), .stoppedSending(_, _, let reason), .peerCannot(_, let reason): return reason
        default: return nil
        }
    }
    static let category = "clipboard"
    /// What the decision log says. Names Macs, short transfer numbers, reasons
    /// and size buckets only: never contents, names, types or exact sizes.
    var line: String {
        func id(_ value: UUID?) -> String { value.map { " " + String($0.uuidString.prefix(8)) } ?? "" }
        func because(_ reason: DeskClipboardReason) -> String { " because " + reason.text }
        switch self {
        case .announced(let to): return "Told \(to.joined(separator: ", ")) about a new copy on this Mac"
        case .notAnnounced(let reason): return "Kept a new copy on this Mac to itself" + because(reason)
        case .waiting(let from): return "The newest copy is on \(from); ⌃⌥⌘V brings it here"
        case .newerElsewhere(let from): return "The newest copy is on \(from) and cannot be brought over"
        case .fetching(let from, let transfer): return "Bringing the newest copy from \(from), transfer\(id(transfer))"
        case .received(let from, let transfer, let size): return "Brought the newest copy from \(from), transfer\(id(transfer)), \(size)"
        case .refusedBy(let from, let transfer, let reason): return "\(from) declined to send its copy\(transfer == nil ? "" : ", transfer" + id(transfer))" + because(reason)
        case .failed(let from, let transfer, let reason, let detail):
            return "Stopped bringing the copy from \(from), transfer\(id(transfer))" + because(reason) + (detail.map { " (\($0))" } ?? "")
        case .discarded(let transfer, let reason): return "Did not use transfer\(id(transfer))" + because(reason)
        case .bringing(let from): return "Bringing over the newest copy, from \(from)"
        case .nothingWaiting: return "Bring over did nothing: no newer copy is waiting on another Mac"
        case .notBringing(let reason): return "Did not bring over the newest copy" + because(reason)
        case .askedToBringOver(let on): return "Asked \(on), where typing goes, to bring over the newest copy"
        case .sent(let to, let transfer, let size): return "Sent this Mac's newest copy to \(to), transfer\(id(transfer)), \(size)"
        case .refused(let to, let transfer, let reason): return "Declined to send this Mac's copy to \(to), transfer\(id(transfer))" + because(reason)
        case .stoppedSending(let to, let transfer, let reason): return "Stopped sending to \(to), transfer\(id(transfer))" + because(reason)
        case .peerSupports(let name, let format): return "\(name) shares copies (format \(format))"
        case .peerCannot(let name, let reason): return "Copies are not shared with \(name)" + because(reason)
        case .cleaned(let count): return "Removed \(count) staged \(count == 1 ? "copy" : "copies") of files no longer on the clipboard"
        }
    }
}

/// What a copy is, as announced to the other Macs: its kind and count ("3
/// photos"), a size bucket, and whether it is small text, which alone goes
/// straight onto their clipboards. Never its contents or names.
struct DeskClipboardDescriptor: Equatable {
    enum Kind: UInt8 { case text = 1, image = 2, files = 3 }
    var kind: Kind
    var count: Int
    var small: Bool
    /// An index into `DeskClipboardPolicy.sizeBuckets`; 0 when not known.
    var size: UInt8 = 0
    /// Scott's line: text of 64 KB or less, every representation together.
    static let smallText = 64 * 1024

    /// From a copy's plan and the bytes it would send.
    static func describe(_ plan: [[DeskClipboardType]], bytes: Int) -> Self {
        let images = plan.filter { $0.contains { $0.isImage } }.count
        if images > 0 { return .init(kind: .image, count: images, small: false, size: DeskClipboardPolicy.sizeIndex(bytes)) }
        return .init(kind: .text, count: 1, small: bytes <= smallText, size: DeskClipboardPolicy.sizeIndex(bytes))
    }
    /// The size bucket in words, or nil when not known.
    var sizeText: String? { DeskClipboardPolicy.sizeBuckets.indices.contains(Int(size) - 1) ? DeskClipboardPolicy.sizeBuckets[Int(size) - 1].name : nil }
}

/// How much Perch carries. Conservative first values; each is recorded in
/// TODO.md as Scott's to change.
struct DeskClipboardLimits {
    var plainText = 2 * 1024 * 1024
    /// Each rich text or HTML representation.
    var richText = 8 * 1024 * 1024
    /// The one image representation sent per item.
    var image = 32 * 1024 * 1024
    /// Everything in one copy together, before compression.
    var total = 40 * 1024 * 1024
    var items = 16

    func cap(_ type: DeskClipboardType) -> Int {
        switch type {
        case .plainText: return plainText
        case .richText, .html: return richText
        case .png, .tiff, .jpeg: return image
        }
    }
}

enum DeskClipboardPolicy {
    /// Which representations to read from each item, or why the copy is
    /// withheld. Decided from the types alone, so a concealed copy is refused
    /// before any of its data is read into Perch.
    enum Assessment: Equatable {
        case withheld(DeskClipboardReason)
        case share([[DeskClipboardType]])
        /// Files: their names first, then each file, into Perch's staging folder.
        case files
    }
    static func assess(_ items: [[String]], limits: DeskClipboardLimits = .init()) -> Assessment {
        let all = Set(items.flatMap { $0 })
        // Order matters only for which single reason is named; every marker
        // withholds the copy.
        if all.contains(DeskClipboardMarker.concealed) || !all.isDisjoint(with: DeskClipboardMarker.legacyConcealed) { return .withheld(.concealed) }
        if all.contains(DeskClipboardMarker.transient) || !all.isDisjoint(with: DeskClipboardMarker.legacyTransient) { return .withheld(.transient) }
        if all.contains(DeskClipboardMarker.autoGenerated) { return .withheld(.autoGenerated) }
        // A copy Perch brought from another Mac is never offered again.
        if all.contains(DeskClipboardMarker.received) { return .withheld(.received) }
        // A copy of files carries their names and icons too, which must never
        // be pasted in place of the files themselves.
        if all.contains(DeskClipboardMarker.fileURL) { return .files }
        if all.contains(DeskClipboardMarker.legacyFileNames) { return .withheld(.unsupported) }
        guard !items.isEmpty else { return .withheld(.noCopy) }
        guard items.count <= limits.items else { return .withheld(.tooLarge) }
        let plan = items.map { types -> [DeskClipboardType] in
            let text = [DeskClipboardType.plainText, .richText, .html].filter { types.contains($0.identifier) }
            let image = DeskClipboardType.imagePreference.first { types.contains($0.identifier) }
            return text + (image.map { [$0] } ?? [])
        }
        guard plan.contains(where: { !$0.isEmpty }) else { return .withheld(.unsupported) }
        return .share(plan)
    }

    /// Coarse sizes: what the log and an announcement say, never the number.
    static let sizeBuckets: [(below: Int, name: String)] = [
        (64 * 1024, "under 64 KB"), (1024 * 1024, "64 KB to 1 MB"), (8 * 1024 * 1024, "1 to 8 MB"),
        (32 * 1024 * 1024, "8 to 32 MB"), (256 * 1024 * 1024, "32 to 256 MB"), (Int.max, "over 256 MB")]
    /// The bucket's index, counting from 1.
    static func sizeIndex(_ bytes: Int) -> UInt8 { UInt8((sizeBuckets.firstIndex { bytes < $0.below } ?? sizeBuckets.count - 1) + 1) }
    static func sizeBucket(_ bytes: Int) -> String { sizeBuckets[Int(sizeIndex(bytes)) - 1].name }
}
