#!/bin/bash
# Passive comparison of the two input-idle clocks. No input, assertions,
# preference changes, permission prompts, or full configuration-profile dumps.
set -eu

duration=720
interval=5
output=""
while [ "$#" -gt 0 ]; do
    case "$1" in
        --seconds|--interval|--output)
            [ "$#" -ge 2 ] || { echo "Missing value for $1" >&2; exit 2; }
            case "$1" in
                --seconds) duration="$2" ;;
                --interval) interval="$2" ;;
                --output) output="$2" ;;
            esac
            shift 2 ;;
        --help)
            echo "Usage: $0 [--seconds 720] [--interval 5] [--output report.txt]"
            echo "Run on the Mac that locks, with Prevent idle lock enabled."
            echo "Leave it untouched through its normal timeout, then unlock normally."
            echo "The default capture lasts 12 minutes and saves a report on the Desktop."
            exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done
case "$duration:$interval" in
    *[!0-9:]*|:*|*:) echo "Seconds and interval must be positive integers." >&2; exit 2 ;;
esac
[ "$duration" -ge 1 ] && [ "$duration" -le 3600 ] &&
    [ "$interval" -ge 1 ] && [ "$interval" -le 60 ] || {
    echo "Use 1–3600 seconds and a 1–60 second interval." >&2; exit 2;
}
duration=$((10#$duration))
interval=$((10#$interval))
[ -n "$output" ] || output="$HOME/Desktop/perch-idle-lock-$(date +%Y%m%d-%H%M%S).txt"
# Never replace an earlier report.
(set -C; : > "$output") || exit 1
exec > >(/usr/bin/tee -a "$output") 2>&1

echo "Perch idle-lock diagnosis — read-only"
echo "Started: $(date '+%Y-%m-%d %H:%M:%S %z')"
echo "Report: $output"
echo "macOS: $(/usr/bin/sw_vers -productVersion) ($( /usr/bin/sw_vers -buildVersion))"
echo "Duration: $duration seconds. Leave this Mac untouched through its normal lock."
echo "No mouse movement, keystrokes, or power assertions are generated by this tool."
echo "Input counters may include Perch and other apps; they do not prove a lock's cause."
echo
echo "Installed app (the running process may be older):"
for key in CFBundleShortVersionString CFBundleVersion; do
    value=$(/usr/libexec/PlistBuddy -c "Print :$key" /Applications/Perch.app/Contents/Info.plist 2>/dev/null) || value="unavailable"
    echo "  $key: $value"
done
echo "Saved Prevent idle lock: $(/usr/bin/defaults read local.scott.perch sleep.preventIdleLock 2>/dev/null || echo unavailable)"
echo "Running app path(s):"
/usr/bin/pgrep -fl '/Perch[^/]*/Contents/MacOS/Perch$' || true
echo
echo "Enrollment status:"
/usr/bin/profiles status -type enrollment || true
echo "Screen saver preferences (missing values do not rule out managed policy):"
for key in idleTime askForPassword askForPasswordDelay loginWindowIdleTime; do
    value=$(/usr/bin/defaults read com.apple.screensaver "$key" 2>/dev/null) || value="not reported"
    hosted=$(/usr/bin/defaults -currentHost read com.apple.screensaver "$key" 2>/dev/null) || hosted="not reported"
    echo "  $key: default=$value; currentHost=$hosted"
done
echo
echo "Each sample is seconds since input. any-input uses kCGAnyInputEventType (0xffffffff), not the null event type."
echo "timestamp | IORegistry HID idle | CG session any-input | CG HID any-input | screen-locked flag"
capture_started=$(date '+%Y-%m-%d %H:%M:%S')
start=$SECONDS
while :; do
    hid=$(/usr/sbin/ioreg -r -d 1 -c IOHIDSystem | /usr/bin/awk '
        /"HIDIdleTime" =/ {printf "%.1f", $NF / 1000000000; found=1; exit}
        END {if (!found) printf "unknown"}')
    clocks=$(/usr/bin/osascript -l JavaScript -e '
        ObjC.import("CoreGraphics");
        var session = $.CGEventSourceSecondsSinceLastEventType(0, 0xffffffff);
        var hid = $.CGEventSourceSecondsSinceLastEventType(1, 0xffffffff);
        var locked = "not reported";
        try {
            var state = ObjC.deepUnwrap($.CGSessionCopyCurrentDictionary());
            if (state && state.CGSSessionScreenIsLocked !== undefined)
                locked = state.CGSSessionScreenIsLocked ? "yes" : "no";
        } catch (_) {}
        [Number(session).toFixed(1), Number(hid).toFixed(1), locked].join(" | ");
    ' 2>/dev/null) || clocks="unavailable | unavailable | unavailable"
    echo "$(date '+%Y-%m-%d %H:%M:%S %z') | $hid | $clocks"
    remaining=$((duration - (SECONDS - start)))
    [ "$remaining" -gt 0 ] || break
    delay=$interval
    [ "$remaining" -ge "$delay" ] || delay=$remaining
    /bin/sleep "$delay"
done
echo
echo "Perch screen lock/unlock records during the capture:"
/usr/bin/log show --start "$capture_started" --style compact --info --predicate \
    'subsystem == "local.scott.perch" AND (eventMessage CONTAINS "screen.lock:" OR eventMessage CONTAINS "screen.unlock:")' || true
echo
echo "The current Perch log may say a low HID counter rules out idle lock. That inference is unproven; compare the session counter too."
echo "Finished: $(date '+%Y-%m-%d %H:%M:%S %z')"
echo "Report saved to: $output"
